baseURL = "https://andrew0x00.vercel.app"
title   = "Hi, I'm André"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[services]
  [services.rss]
      # Maximum number of items in the RSS feed.
      limit = 42

#   [services.disqus]
#     shortname = 'your-disqus-shortname'
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  #
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]

  # Home subtitle of the index page.
  #
  homeSubtitle = "I’ll use this blog to share write-ups and anything interesting I come across."

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Enable theme toggle
  #
  # This options enables the theme toggle for the theme.
  # Per default, this option is off.
  # The theme is respecting the prefers-color-scheme of the operating system.
  # With this option on, the page user is able to set the scheme he wants.
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Global language menu
  #
  # Enables the global language menu.
  #
  # enableGlobalLanguageMenu = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Integrate Plausible.io
  # plausibleDataDomain = 'test.com'
  # plausibleScriptSource = 'https://plausible.io/js/script.js'

  [params.author]
    name = "andrew0x00"

  # Custom footer
  # If you want, you can easily override the default footer with your own content.
  
  [params.footer]
    trademark = 2025
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText
    # logoCursorPathname = true

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Startpage portrait 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Uncomment this if you want a portrait on your start page
  #
  # [params.portrait]
  #   path     = "/img/image.jpg"
  #   alt      = "Portrait"
  #   maxWidth = "50px"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Addon: Commento
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Commento is more than just a comments widget you can embed —
  # it’s a return to the roots of the internet.
  # An internet without the tracking and invasions of privacy.
  # An internet that is simple and lightweight.
  # An internet that is focused on interesting discussions, not ads.
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Addon: Utteranc.es
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Utteranc.es is a lightweight comments widget built on GitHub issues.
  # See https://utteranc.es/ for documentation
  # Uncomment this to enable Utteranc.es.
  #
  # [params.utterances]
  #   Your GitHub repository
  #
  #   repository = ""
  #
  #   label used for GitHub issues
  #
  #   label      = ""
  #
  #   Blog Post <-> Issue mapping. This parameter is optional. Possible values are:
  #      - pathname
  #      - url
  #      - title
  #      - og:title
  #      - issue number
  #      - specific term
  #
  #   issueTerm  = ""
  #
  #   Theme used: possible values are:
  #      - github-light
  #      - github-dark
  #      - preferred-color-scheme
  #      - github-dark-orange
  #      - icy-dark
  #      - dark-blue
  #      - photon-dark
  #      - boxy-light
  #      - gruvbox-dark
  #
  # theme      = ""
  #

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Addon: Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  [[params.social]]
    name = "email"
    url  = "mailto:andre.luiz.ribeiro@pm.me"

  [[params.social]]
    name = "github"
    url  = "https://github.com/wh0isandrew"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/andr3l/"


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.pt]
    contentDir = 'content/pt-br'
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Portuguese'
    weight = 1
  [languages.pt.params]
    subtitle  = "Vou usar esse blog para compartilhar writeups e qualquer coisa intessante que eu encontrar."
  [languages.en]
    weight    = 2
    languageCode = 'en-US'
    contentDir = 'content/en'
    languageName = 'English'
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  [languages.en.params]
    subtitle  = "I’ll use this blog to share writeups and anything interesting I come across."

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"